version: 2
updates:
- package-ecosystem: pip
  directory: "/{{cookiecutter.directory_name}}"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: black
    versions:
    - 21.4b0
    - 21.4b1
