[tool.poetry]
name = "{{ cookiecutter.directory_name }}"
version = "0.1.0"
description = "{{ cookiecutter.description }}"
authors = []
readme = "{{ cookiecutter.readme }}"
license = "{{ cookiecutter.license }}"

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.0"

[tool.poetry.dev-dependencies]
pytest = "^6.0.1"
flake8 = "^3.7.9"
flake8-docstrings = "^1.5.0"
black = "^19.10b0"
isort = "^4.3.21"
notebook = "^6.0.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
