[tool.poetry]
name = "{{ cookiecutter.directory_name }}"
version = "{{ cookiecutter.poetry.version }}"
description = "{{ cookiecutter.poetry.description }}"
authors = "{{ cookiecutter.poetry.authors }}"
readme = "{{ cookiecutter.poetry.readme }}"
license = "{{ cookiecutter.poetry.license }}"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.3.5"
flake8 = "^3.7.9"
black = "^19.10b0"
isort = "^4.3.21"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
